# Generated by Django 5.0.6 on 2024-06-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_recommendation_clothing_item_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField()),
                ("rating", models.PositiveIntegerField()),
                ("helpful", models.PositiveIntegerField()),
                ("diverse", models.PositiveIntegerField()),
                ("usage", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
