# Generated by Django 5.0.6 on 2024-06-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_recommendationrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationrating",
            name="gender",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recommendationrating",
            name="image",
            field=models.ImageField(default="", upload_to="recommendation_images/"),
            preserve_default=False,
        ),
    ]
