# Generated by Django 5.0.6 on 2024-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_recommendationrating_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationrating",
            name="image",
            field=models.TextField(),
        ),
    ]
